language: csharp
solution: Parquet.Plus.sln
mono: none
dist: xenial
os: linux
dotnet: 3.1
install:
 - dotnet restore
script:
 - dotnet build --configuration Release
 - dotnet test Parquet.Plus.Tests/Parquet.Plus.Tests.csproj
 - dotnet nuget push Parquet.Plus/bin/Release/*.nupkg -s "https://nuget.org" -k $NUGET_API_KEY --skip-duplicate